name = "indiaesque"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
